/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package batchFileOperations;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jonathon
 */
public class RenameFromList extends javax.swing.JFrame {

    private Files newFiles;
    private JFileChooser chooseFiles;

    /**
     * Creates new form RenameFromList
     */
    public RenameFromList() {
        initComponents();

        chooseFiles = new JFileChooser();
        chooseFiles.setFileFilter(Filters.getVideoFilter());
        chooseFiles.setMultiSelectionEnabled(true);
        chooseFiles.showOpenDialog(null);
        newFiles = new Files(chooseFiles.getSelectedFiles());
        DefaultListModel selectedFiles = new DefaultListModel();
        for (int i = 0;
                i < newFiles.getLength();
                i++) {
            selectedFiles.addElement(newFiles.getOriginalFileNames(i));
        }

        jLstOriginalFiles.setListData(newFiles.getFileNames());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLstOriginalFiles = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstNewNames = new javax.swing.JList();
        jDDLSelectOperation = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLstOriginalFiles.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLstOriginalFiles.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLstOriginalFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstOriginalFilesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLstOriginalFiles);

        jButton1.setText("Rename");

        jLstNewNames.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jLstNewNames);

        jDDLSelectOperation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Insert", "Modify", "Replace" }));
        jDDLSelectOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDDLSelectOperationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jDDLSelectOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDDLSelectOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLstOriginalFilesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstOriginalFilesValueChanged
        jLstNewNames.setListData(newFiles.getFileNames(jLstOriginalFiles.getSelectedIndices()));
    }//GEN-LAST:event_jLstOriginalFilesValueChanged

    private void jDDLSelectOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDDLSelectOperationActionPerformed
        Container container = getContentPane();
        
        container.add(new Insert(), BorderLayout.CENTER);
        container.setSize(400, 300);
        JOptionPane.showInputDialog(container, "Enter bitch");
    }//GEN-LAST:event_jDDLSelectOperationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenameFromList().setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jDDLSelectOperation;
    private javax.swing.JList jLstNewNames;
    private javax.swing.JList jLstOriginalFiles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
